import { existsSync, rmSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import type { CloudDomain } from "./cloud.js"

/**
 * Generated artifacts for Postboi Cloud, installed *inside* the postboi package in
 * node_modules — no project file, nothing to commit or gitignore:
 *
 * - `register.d.ts`: a `Register` augmentation narrowing every `from` field to the
 *   account's sending address plus its domains. Pending domains are included
 *   deliberately: you write the code while DNS propagates, and the API enforces delivery
 *   either way — the type answers "is this plausibly my address", not "will it deliver".
 * - `register.js`: the account's publishable captcha key, which is what lets the
 *   framework `<Captcha />` components work with no props.
 */

/** The placeholder `.d.ts` the package ships, overwritten with the generated union. */
export const TYPES_TARGET = join("node_modules", "postboi", "dist", "register.d.ts")

/** The placeholder runtime module, overwritten with the account's publishable key. */
export const RUNTIME_TARGET = join("node_modules", "postboi", "dist", "register.js")

const HEADER =
	"// Generated by `bunx postboi sync` — do not edit. Re-run it after adding or removing domains.\n"

/** Union members for one address/domain: the bare form plus the `"Name <…>"` form. */
function members(send_address: string | undefined, domains: Array<CloudDomain>): Array<string> {
	const out: Array<string> = []
	if (send_address) out.push(JSON.stringify(send_address), `\`\${string}<${send_address}>\``)
	for (const d of domains) out.push(`\`\${string}@${d.domain}\``, `\`\${string}@${d.domain}>\``)
	return out
}

/** The `from` augmentation block, or empty when the account has nothing to send from. */
function register_block(send_address: string | undefined, domains: Array<CloudDomain>): string {
	const union = members(send_address, domains)
	if (union.length === 0) return ""
	return `declare module "postboi" {
	interface Register {
		from:
${union.map((m) => `\t\t\t| ${m}`).join("\n")}
	}
}

`
}

/**
 * The full generated `register.d.ts` source, or null when there's nothing to generate.
 * The `captcha_key` declaration mirrors the shipped placeholder so imports keep
 * type-checking, and the `export` makes this a module, so `declare module` *augments*
 * the package types instead of replacing them wholesale.
 */
export function render_types(
	send_address: string | undefined,
	domains: Array<CloudDomain>,
	captcha_key?: string
): string | null {
	const register = register_block(send_address, domains)
	if (!register && !captcha_key) return null
	return `${HEADER}${register}export declare const captcha_key: string | undefined
`
}

/** The generated `register.js` source: the baked publishable key. */
export function render_runtime(captcha_key: string | undefined): string {
	return `${HEADER}export const captcha_key = ${captcha_key ? JSON.stringify(captcha_key) : "undefined"}
`
}

/** Remove-then-write: pnpm hard-links package files into its global store, and an
 * in-place write would corrupt the shared copy. Unlinking gives us a fresh inode. */
function replace(target: string, source: string): void {
	rmSync(target)
	writeFileSync(target, source)
}

/**
 * Overwrite the installed package's placeholders with the generated types and runtime
 * key. Null when there's nothing to write — no addresses and no key, or postboi isn't
 * installed here yet.
 */
export function write_types(
	send_address: string | undefined,
	domains: Array<CloudDomain>,
	captcha_key?: string
): string | null {
	const source = render_types(send_address, domains, captcha_key)
	if (!source || !existsSync(TYPES_TARGET)) return null
	replace(TYPES_TARGET, source)
	if (existsSync(RUNTIME_TARGET)) replace(RUNTIME_TARGET, render_runtime(captcha_key))
	return TYPES_TARGET
}

/** How a chosen `from` relates to the account: sendable, pending verification, or foreign. */
export function from_status(
	input: string,
	send_address: string | undefined,
	domains: Array<CloudDomain>
): { level: "ok" } | { level: "pending" | "unknown"; domain: string } {
	const email = (/<([^>]+)>/.exec(input)?.[1] ?? input).trim().toLowerCase()
	if (send_address && email === send_address.toLowerCase()) return { level: "ok" }
	const domain = email.split("@")[1] ?? ""
	const match = domains.find((d) => d.domain.toLowerCase() === domain)
	if (!match) return { level: "unknown", domain: domain || input }
	return match.status === "verified" ? { level: "ok" } : { level: "pending", domain: match.domain }
}
