import { existsSync, rmSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import type { CloudDomain } from "./cloud.js"

/**
 * Generated artifacts for Postboi Cloud, installed *inside* the postboi package in
 * node_modules — no project file, nothing to commit or gitignore:
 *
 * - `register.d.ts`: a `Register` augmentation narrowing every `from` field to the
 *   account's sending address plus its domains. Pending domains are included
 *   deliberately: you write the code while DNS propagates, and the API enforces delivery
 *   either way — the type answers "is this plausibly my address", not "will it deliver".
 * - `register.js`: the account's publishable captcha key, which is what lets the
 *   framework `<Captcha />` components work with no props.
 */

/** The placeholder `.d.ts` the package ships, overwritten with the generated union. */
export const TYPES_TARGET = join("node_modules", "postboi", "dist", "register.d.ts")

/** The placeholder runtime module, overwritten with the account's publishable key. */
export const RUNTIME_TARGET = join("node_modules", "postboi", "dist", "register.js")

const HEADER =
	"// Generated by `bunx postboi sync` — do not edit. Re-run it after adding or removing domains.\n"

/** Union members for one address/domain: the bare form plus the `"Name <…>"` form. */
function members(send_address: string | undefined, domains: Array<CloudDomain>): Array<string> {
	const out: Array<string> = []
	if (send_address) out.push(JSON.stringify(send_address), `\`\${string}<${send_address}>\``)
	for (const d of domains) out.push(`\`\${string}@${d.domain}\``, `\`\${string}@${d.domain}>\``)
	return out
}

/** The `from` augmentation block, or empty when the account has nothing to send from. */
function register_block(send_address: string | undefined, domains: Array<CloudDomain>): string {
	const union = members(send_address, domains)
	if (union.length === 0) return ""
	return `declare module "postboi" {
	interface Register {
		from:
${union.map((m) => `\t\t\t| ${m}`).join("\n")}
	}
}

`
}

/**
 * The full generated `register.d.ts` source, or null when the account has nothing to send
 * from. The `captcha_key` declaration mirrors the shipped placeholder so imports keep
 * type-checking, and the `export` makes this a module, so `declare module` *augments*
 * the package types instead of replacing them wholesale.
 */
export function render_types(
	send_address: string | undefined,
	domains: Array<CloudDomain>
): string | null {
	const register = register_block(send_address, domains)
	if (!register) return null
	return `${HEADER}${register}export declare const captcha_key: string | undefined
`
}

/** The generated `register.js` source: the baked publishable key. */
export function render_runtime(captcha_key: string): string {
	return `${HEADER}export const captcha_key = ${JSON.stringify(captcha_key)}
`
}

/** Remove-then-write: pnpm hard-links package files into its global store, and an
 * in-place write would corrupt the shared copy. Unlinking gives us a fresh inode. */
function replace(target: string, source: string): void {
	rmSync(target)
	writeFileSync(target, source)
}

/**
 * Overwrite the installed package's placeholder types with the generated `from` union.
 * Null when there's nothing to write — no addresses, or postboi isn't installed here yet.
 */
export function write_types(
	send_address: string | undefined,
	domains: Array<CloudDomain>
): string | null {
	const source = render_types(send_address, domains)
	if (!source || !existsSync(TYPES_TARGET)) return null
	replace(TYPES_TARGET, source)
	return TYPES_TARGET
}

/**
 * Bake the publishable captcha key into the installed package's runtime placeholder —
 * what makes `<Captcha />` prop-free. Null with no key, or when postboi isn't installed
 * here yet. Never bakes an empty value over a previous key.
 */
export function write_runtime(captcha_key: string | undefined): string | null {
	if (!captcha_key || !existsSync(RUNTIME_TARGET)) return null
	replace(RUNTIME_TARGET, render_runtime(captcha_key))
	return RUNTIME_TARGET
}

/** Read the publishable key out of a `postboi.config.*` source (`captcha: { key }`). */
export function config_captcha_key(source: string): string | undefined {
	return /captcha\s*:\s*\{[^}]*?\bkey\s*:\s*["']([^"']+)["']/.exec(source)?.[1]
}

/**
 * Surgically write the publishable key into a `postboi.config.*` source: replace an
 * existing `captcha.key`, extend an existing `captcha` block, or add one just inside
 * `config({`. Null when the file's shape isn't recognised — the caller prints a
 * merge-it-yourself hint instead of clobbering a hand-edited config.
 */
export function upsert_captcha_key(source: string, key: string): string | null {
	const literal = JSON.stringify(key)
	const existing = /(captcha\s*:\s*\{[^}]*?\bkey\s*:\s*)(["'][^"']*["'])/
	if (existing.test(source)) return source.replace(existing, `$1${literal}`)
	const block = /(captcha\s*:\s*\{)/
	if (block.test(source)) return source.replace(block, `$1 key: ${literal},`)
	const open = /(\bconfig\s*\(\s*\{\s*\n)/
	if (open.test(source)) return source.replace(open, `$1\tcaptcha: { key: ${literal} },\n`)
	return null
}

/** How a chosen `from` relates to the account: sendable, pending verification, or foreign. */
export function from_status(
	input: string,
	send_address: string | undefined,
	domains: Array<CloudDomain>
): { level: "ok" } | { level: "pending" | "unknown"; domain: string } {
	const email = (/<([^>]+)>/.exec(input)?.[1] ?? input).trim().toLowerCase()
	if (send_address && email === send_address.toLowerCase()) return { level: "ok" }
	const domain = email.split("@")[1] ?? ""
	const match = domains.find((d) => d.domain.toLowerCase() === domain)
	if (!match) return { level: "unknown", domain: domain || input }
	return match.status === "verified" ? { level: "ok" } : { level: "pending", domain: match.domain }
}
