import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import type { PostboiDomain, PostboiForm } from "./postboi.js"

/**
 * Generated artifacts for the Postboi provider, installed *inside* the postboi package in
 * node_modules — no project file, nothing to commit or gitignore:
 *
 * - `register.d.ts`: a `Register` augmentation narrowing every `from` field to the
 *   account's sending address plus its domains, every WhatsApp `template` to the
 *   names approved on Meta or Twilio, and every `form` to the account's forms by
 *   name and id. Pending domains are included
 *   deliberately: you write the code while DNS propagates, and the API enforces delivery
 *   either way — the type answers "is this plausibly my address", not "will it deliver".
 * - `register.js`: the account's publishable captcha key, which is what lets the
 *   framework `<Captcha />` components work with no props, plus Twilio's name→Content SID
 *   map, which is what lets a Twilio send name its template instead of quoting an `HX…`.
 */

/** The placeholder `.d.ts` the package ships, overwritten with the generated union. */
export const TYPES_TARGET = join("node_modules", "postboi", "dist", "register.d.ts")

/** The placeholder runtime module, overwritten with the account's publishable key. */
export const RUNTIME_TARGET = join("node_modules", "postboi", "dist", "register.js")

const HEADER =
	"// Generated by `bunx postboi sync` — do not edit. Re-run it after a domain, template or form changes.\n"

/** Union members for one address/domain: the bare form plus the `"Name <…>"` form. */
function members(send_address: string | undefined, domains: Array<PostboiDomain>): Array<string> {
	const out: Array<string> = []
	if (send_address) out.push(JSON.stringify(send_address), `\`\${string}<${send_address}>\``)
	for (const d of domains) out.push(`\`\${string}@${d.domain}\``, `\`\${string}@${d.domain}>\``)
	return out
}

/** One `Register` member: `name:` followed by its union, one member per line. */
function member(name: string, union: Array<string>): string {
	return `\t\t${name}:\n${union.map((m) => `\t\t\t| ${m}`).join("\n")}\n`
}

/**
 * The `template_variables` member: each template's placeholders as a union it must be
 * called with. Templates with no placeholders found are left out entirely — an absent
 * entry falls back to accepting any variables, whereas an empty one would reject a valid
 * send, and "we couldn't read this template's body" must not break compiling code.
 */
function variables_member(variables: Record<string, Array<string>>): string {
	const rows = Object.entries(variables)
		.filter(([, names]) => names.length > 0)
		.map(([template, names]) => {
			const union = names.map((n) => JSON.stringify(n)).join(" | ")
			return `\t\t\t${JSON.stringify(template)}: ${union}\n`
		})
	if (rows.length === 0) return ""
	return `\t\ttemplate_variables: {\n${rows.join("")}\t\t}\n`
}

/**
 * Union members for the account's forms: each current name, then each id. The ids are
 * already covered by the `form_${string}` pattern the type carries — listing them is for
 * autocomplete, so an id can be picked rather than pasted.
 */
function form_members(forms: Array<PostboiForm>): Array<string> {
	return [...forms.map((f) => JSON.stringify(f.name)), ...forms.map((f) => JSON.stringify(f.id))]
}

/**
 * The `Register` augmentation block, or empty when there's nothing to narrow — no
 * sending addresses, no templates and no forms.
 */
function register_block(
	send_address: string | undefined,
	domains: Array<PostboiDomain>,
	templates: Array<string>,
	variables: Record<string, Array<string>>,
	keep_from: Array<string>,
	forms: Array<PostboiForm> | undefined,
	keep_forms: Array<string>,
	provider: string | undefined
): string {
	const blocks: Array<string> = []
	// Which provider the project sends through, so the Postboi-only options (`form`)
	// can be a type error elsewhere. Undefined is "no opinion" and keeps the last one.
	if (provider) blocks.push(member("provider", [JSON.stringify(provider)]))
	// Nothing to compute a union from means this run didn't reach the account, not that the
	// account lost its addresses — keep the ones already generated.
	const resolved = members(send_address, domains)
	const from = resolved.length > 0 ? resolved : keep_from
	if (from.length > 0) blocks.push(member("from", from))
	if (templates.length > 0) {
		blocks.push(
			member(
				"template",
				templates.map((t) => JSON.stringify(t))
			)
		)
		blocks.push(variables_member(variables))
	}
	// Forms differ from addresses in that an empty list is an answer: an account with no
	// forms gets no `form` member, and `form` widens back to any string so the first send
	// can create one. Only a run that couldn't ask (undefined) keeps the last generated
	// names, so a blip doesn't loosen a type that was narrow yesterday.
	const form = forms ? form_members(forms) : keep_forms
	if (form.length > 0) blocks.push(member("form", form))
	if (blocks.length === 0) return ""
	return `declare module "postboi" {
	interface Register {
${blocks.join("")}	}
}

`
}

/**
 * The full generated `register.d.ts` source, or null when the account has nothing to send
 * from. The `captcha_key` declaration mirrors the shipped placeholder so imports keep
 * type-checking, and the `export` makes this a module, so `declare module` *augments*
 * the package types instead of replacing them wholesale.
 */
export function render_types(
	send_address: string | undefined,
	domains: Array<PostboiDomain>,
	templates: Array<string> = [],
	variables: Record<string, Array<string>> = {},
	keep_from: Array<string> = [],
	forms: Array<PostboiForm> | undefined = undefined,
	keep_forms: Array<string> = [],
	provider: string | undefined = undefined
): string | null {
	const register = register_block(
		send_address,
		domains,
		templates,
		variables,
		keep_from,
		forms,
		keep_forms,
		provider
	)
	if (!register) return null
	return `${HEADER}${register}export declare const captcha_key: string | undefined
export declare const whatsapp_templates: Record<string, string>
export declare const vapid_public_key: string | undefined
`
}

/** The generated `register.js` source: the baked keys and template SIDs. */
export function render_runtime(
	captcha_key: string | undefined,
	template_sids: Record<string, string> = {},
	vapid_public_key: string | undefined = undefined
): string {
	return `${HEADER}export const captcha_key = ${JSON.stringify(captcha_key)}
export const whatsapp_templates = ${JSON.stringify(template_sids)}
export const vapid_public_key = ${JSON.stringify(vapid_public_key)}
`
}

/** Remove-then-write: pnpm hard-links package files into its global store, and an
 * in-place write would corrupt the shared copy. Unlinking gives us a fresh inode. */
function replace(target: string, source: string): void {
	rmSync(target)
	writeFileSync(target, source)
}

/**
 * Both writers below rewrite a whole file, but no single run computes all of it: a
 * tokenless sync knows the templates and not the domains, a Meta project has no SIDs, and
 * an unreachable API knows nothing at all. Blindly writing what this run resolved would
 * quietly delete what the last one did — a flaky network turning into "why is `from` no
 * longer type-checked" or a Twilio send failing on an unresolved name. So each writer
 * carries forward what it wasn't given, and only ever replaces a value it actually has.
 */

/** Read back one union {@link member} wrote, so a run that couldn't recompute it keeps it. */
function parse_member(source: string, name: string): Array<string> {
	const block = new RegExp(`\\n\\t\\t${name}:\\n((?:\\t\\t\\t\\| .*\\n)+)`).exec(source)
	if (!block) return []
	return block[1]
		.split("\n")
		.map((line) => line.replace(/^\t\t\t\| /, "").trim())
		.filter(Boolean)
}

/** Read back the `from:` union, so a run without domains keeps it. */
export function parse_from(source: string): Array<string> {
	return parse_member(source, "from")
}

/** Read back the `form:` union, so a run that couldn't list the forms keeps it. */
export function parse_forms(source: string): Array<string> {
	return parse_member(source, "form")
}

/** Read back the `provider:` marker, so a run with no config to read keeps it. */
export function parse_provider(source: string): string | undefined {
	const [literal] = parse_member(source, "provider")
	try {
		return literal ? (JSON.parse(literal) as string) : undefined
	} catch {
		return undefined
	}
}

/** Read back what {@link render_runtime} baked. */
export function parse_runtime(source: string): {
	captcha_key?: string
	sids: Record<string, string>
	vapid_public_key?: string
} {
	const key = /captcha_key = "([^"]*)"/.exec(source)?.[1]
	const vapid = /vapid_public_key = "([^"]*)"/.exec(source)?.[1]
	const map = /whatsapp_templates = (\{.*\})/.exec(source)?.[1]
	try {
		return {
			captcha_key: key,
			vapid_public_key: vapid,
			sids: map ? (JSON.parse(map) as Record<string, string>) : {},
		}
	} catch {
		// A hand-edited or half-written file is no worse than none — fall back to empty.
		return { captcha_key: key, vapid_public_key: vapid, sids: {} }
	}
}

/** The installed artifacts' current contents, or empties when they aren't there. */
function installed(target: string): string {
	return existsSync(target) ? readFileSync(target, "utf8") : ""
}

/**
 * Overwrite the installed package's placeholder types with the generated unions. Null when
 * there's nothing to write — no addresses, no templates, or postboi isn't installed here
 * yet. A run that couldn't resolve any addresses keeps the ones already generated.
 */
export function write_types(
	send_address: string | undefined,
	domains: Array<PostboiDomain>,
	templates: Array<string> = [],
	variables: Record<string, Array<string>> = {},
	forms: Array<PostboiForm> | undefined = undefined,
	provider: string | undefined = undefined
): string | null {
	if (!existsSync(TYPES_TARGET)) return null
	const current = installed(TYPES_TARGET)
	const source = render_types(
		send_address,
		domains,
		templates,
		variables,
		parse_from(current),
		forms,
		parse_forms(current),
		provider ?? parse_provider(current)
	)
	if (!source) return null
	replace(TYPES_TARGET, source)
	return TYPES_TARGET
}

/**
 * Bake the publishable captcha key and Twilio's template SIDs into the installed
 * package's runtime placeholder — what makes `<Captcha />` prop-free and lets a Twilio
 * send name its template. Null when there's nothing to bake, or when postboi isn't
 * installed here yet. Never bakes an empty file over a previous one.
 */
export function write_runtime(
	captcha_key: string | undefined,
	template_sids: Record<string, string> = {},
	vapid_public_key: string | undefined = undefined
): string | null {
	if (!existsSync(RUNTIME_TARGET)) return null
	const current = parse_runtime(installed(RUNTIME_TARGET))
	const key = captcha_key ?? current.captcha_key
	const vapid = vapid_public_key ?? current.vapid_public_key
	// An empty map means this run resolved no templates — a Meta project, or a fetch that
	// failed — not that the account's templates are gone. Keeping the last good map is what
	// stops a blip from turning every named Twilio template into an invalid ContentSid.
	const sids = Object.keys(template_sids).length > 0 ? template_sids : current.sids
	if (!key && !vapid && Object.keys(sids).length === 0) return null
	replace(RUNTIME_TARGET, render_runtime(key, sids, vapid))
	return RUNTIME_TARGET
}

/**
 * Read the provider out of a `postboi.config.*` source (`provider: "resend"`) — the config
 * object's own key, not a channel's. `sms: { provider: "twilio" }` says what SMS goes
 * through and nothing about mail, and a config that leaves the top-level one out (the
 * usual Postboi setup) must not be read as sending through Twilio. So a match only counts
 * one brace deep, inside the `config({ … })` call and no deeper.
 */
export function config_provider(source: string): string | undefined {
	for (const match of source.matchAll(/^\s*provider\s*:\s*["']([a-z0-9_-]+)["']/gm)) {
		const before = source.slice(0, match.index)
		const depth = (before.match(/\{/g)?.length ?? 0) - (before.match(/\}/g)?.length ?? 0)
		if (depth <= 1) return match[1]
	}
	return undefined
}

/** Read `default.from` out of a `postboi.config.*` source — the address the project sends as. */
export function config_default_from(source: string): string | undefined {
	return /\bdefault\s*:\s*\{[^}]*?\bfrom\s*:\s*["']([^"']+)["']/.exec(source)?.[1]
}

/** Read the publishable key out of a `postboi.config.*` source (`captcha: { key }`). */
export function config_captcha_key(source: string): string | undefined {
	return /captcha\s*:\s*\{[^}]*?\bkey\s*:\s*["']([^"']+)["']/.exec(source)?.[1]
}

/**
 * Surgically write the publishable key into a `postboi.config.*` source: replace an
 * existing `captcha.key`, extend an existing `captcha` block, or add one just inside
 * `config({`. Null when the file's shape isn't recognised — the caller prints a
 * merge-it-yourself hint instead of clobbering a hand-edited config.
 */
export function upsert_captcha_key(source: string, key: string): string | null {
	const literal = JSON.stringify(key)
	const existing = /(captcha\s*:\s*\{[^}]*?\bkey\s*:\s*)(["'][^"']*["'])/
	if (existing.test(source)) return source.replace(existing, `$1${literal}`)
	const block = /(captcha\s*:\s*\{)/
	if (block.test(source)) return source.replace(block, `$1 key: ${literal},`)
	const open = /(\bconfig\s*\(\s*\{\s*\n)/
	if (open.test(source)) return source.replace(open, `$1\tcaptcha: { key: ${literal} },\n`)
	return null
}

/** How a chosen `from` relates to the account: sendable, pending verification, or foreign. */
export function from_status(
	input: string,
	send_address: string | undefined,
	domains: Array<PostboiDomain>
): { level: "ok" } | { level: "pending" | "unknown"; domain: string } {
	const email = (/<([^>]+)>/.exec(input)?.[1] ?? input).trim().toLowerCase()
	if (send_address && email === send_address.toLowerCase()) return { level: "ok" }
	const domain = email.split("@")[1] ?? ""
	const match = domains.find((d) => d.domain.toLowerCase() === domain)
	if (!match) return { level: "unknown", domain: domain || input }
	return match.status === "verified" ? { level: "ok" } : { level: "pending", domain: match.domain }
}
