import { writeFileSync } from "node:fs"
import { help_markdown } from "../src/cli/help.js"

/**
 * Writes the CLI reference page from the CLI's own help data, so `/raw/cli` cannot say
 * something the binary doesn't. `bun scripts/cli-docs.ts`; `src/cli/help.test.ts` fails
 * when the page on disk is behind.
 */

export const CLI_DOC = "src/site/content/docs/cli.svx"

export function cli_page(): string {
	return `---
title: CLI
name: CLI
description: Every postboi command — setup, the dev inbox, and the whole account from the terminal. Generated from the CLI's own help.
category: Reference
---

<!-- Generated by scripts/cli-docs.ts from src/cli/help.ts — edit there. -->

The \`postboi\` package carries a CLI: \`bunx postboi <command>\` (or \`npx\`). Setup and the
dev tools work with any provider; the account commands need the Postboi provider's
\`POSTBOI_TOKEN\`, which \`init\` writes. Every account command takes \`--json\` for the API's
response as one document, and a failure carries the API's \`code\` — what a script or an
agent should branch on.

${help_markdown()}
## For agents

\`bunx postboi init --agent\` provisions a claimable sandbox account with no prompts and no
sign-in, \`bunx postboi skill\` installs the agent skill that teaches the library, and
\`bunx postboi doctor\` says whether a project is wired. This page is also plain Markdown at
\`/raw/cli\`.
`
}

if (import.meta.main) {
	writeFileSync(CLI_DOC, cli_page())
	console.log(`wrote ${CLI_DOC}`)
}
