import { writeFileSync } from "node:fs"
import { help_markdown } from "../src/cli/help.js"

/**
 * Writes the CLI reference page from the CLI's own help data, so `/raw/cli` cannot say
 * something the binary doesn't. `bun scripts/cli-docs.ts`; `src/cli/help.test.ts` fails
 * when the page on disk is behind.
 */

export const CLI_DOC = "src/site/content/docs/cli.svx"
/** The same table inside the agent skill, loaded on demand rather than on every trigger. */
export const CLI_REFERENCE = "skills/postboi/references/cli.md"

export function cli_page(): string {
	return `---
title: CLI
name: CLI
description: Every postboi command — setup, the dev inbox, and the whole account from the terminal. Generated from the CLI's own help.
category: Reference
---

<!-- Generated by scripts/cli-docs.ts from src/cli/help.ts — edit there. -->

The \`postboi\` package carries a CLI: \`bunx postboi <command>\` (or \`npx\`). Setup and the
dev tools work with any provider; the account commands need the Postboi provider's
\`POSTBOI_TOKEN\`, which \`init\` writes. Every account command takes \`--json\` for the API's
response as one document, and a failure carries the API's \`code\` — what a script or an
agent should branch on.

${help_markdown()}
## For agents

\`bunx postboi init --agent\` provisions a claimable sandbox account with no prompts and no
sign-in, \`bunx postboi skill\` installs the agent skill that teaches the library, and
\`bunx postboi doctor\` says whether a project is wired. This page is also plain Markdown at
\`/raw/cli\`.
`
}

/**
 * The skill's CLI reference: the generated table, then the notes an agent needs that a
 * help text can't carry — what to run first, what never to guess, what is unprompted.
 */
export function cli_reference(): string {
	return `# The CLI

<!-- Generated by scripts/cli-docs.ts from src/cli/help.ts — edit there. -->

\`bunx postboi <command>\` (or \`npx\`). Setup and the dev tools work with any provider; the
account commands need the Postboi provider's \`POSTBOI_TOKEN\`, which \`init\` writes. A bare
noun lists (\`list\` says the same). **Add \`--json\` to any account command** for the API's
response as one JSON document on stdout — parse that rather than the table — and a failure
goes to stderr as \`{ "error": { "message", "code" } }\` with exit 1; branch on the \`code\`
(\`name_taken\`, \`export_paused\`, \`no_token\`, …), never the wording.

${help_markdown()}
## Notes for agents

- **\`doctor\` first and last.** It says whether the project is wired — token, provider,
  \`default.from\`, webhooks, skill — names every fix, and exits 1 on a failure.
- **\`send\` then \`messages <id>\`** proves the pipeline end to end from the terminal; no
  throwaway script. On a sandboxed account \`send\` prints the claim URL — surface it.
- **\`forms\` before naming a form** on a send, so \`contact\` doesn't land beside
  \`Contact form\`. A form is created on first use and matched case-insensitively.
- **Exports** are a hosted feature, downloaded now or emailed on a schedule — the recipe
  and the defaults to state rather than guess are in \`references/exports.md\`.
- **Recipients** upsert the contact and the membership; with names or custom data, or in
  bulk, POST \`/v1/lists/<list>/recipients\` (see \`references/migration.md\`).
- **Suppressions** take an email, or a phone number suppressed per channel: SMS unless
  \`--channel whatsapp\`.
- **\`webhooks add\` then \`sync\`**, which writes the secret to \`POSTBOI_WEBHOOK_SECRET\`;
  \`webhooks rotate <id>\` mints a new one and the old stops verifying at once.
- **A sign-up or sign-in email to receive?** \`inbox\` makes a throwaway address at
  tempboi.email with no token and no account; \`inbox wait --code\` prints the one-time
  code (exit 2 on timeout, 3 when the mail has none), \`--link\` the verify link. Recipe
  in \`https://docs.postboi.app/raw/temp-inbox\`.
- **Deletes are immediate and unprompted** (\`lists delete\` takes the recipients with it).
- **Dashboard-only by design:** API-key management, member roles and billing — send the
  user there rather than trying.
- **No terminal, no prompts:** \`init\` without \`--agent\` refuses to run unattended (exit
  2); \`init --agent\` is the one to run.

Anything richer than the CLI exposes: the REST API at https://api.postboi.app —
\`https://postboi.app/openapi/<tag>.json\` for one feature's slice of the OpenAPI document
(\`exports\`, \`forms\`, \`messages\`, …; the index is \`https://postboi.app/openapi\`), auth
\`Authorization: Bearer $POSTBOI_TOKEN\`, errors always \`{ "message", "code" }\`.
`
}

if (import.meta.main) {
	writeFileSync(CLI_DOC, cli_page())
	writeFileSync(CLI_REFERENCE, cli_reference())
	console.log(`wrote ${CLI_DOC} and ${CLI_REFERENCE}`)
}
